CREATE TABLE students (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id          BIGINT NOT NULL REFERENCES gyms(id),
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    document_id     VARCHAR(50),
    phone           VARCHAR(50),
    email           VARCHAR(150),
    birth_date      DATE,
    sport           VARCHAR(100),
    objective       VARCHAR(150),
    level           VARCHAR(50),
    general_notes   TEXT,
    active          BOOLEAN NOT NULL DEFAULT true,
    started_at      DATE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_students_gym_doc UNIQUE (gym_id, document_id)
);

CREATE INDEX idx_students_gym ON students(gym_id);
CREATE INDEX idx_students_active ON students(gym_id, active);
CREATE INDEX idx_students_search ON students(gym_id, last_name, first_name);

CREATE TABLE student_injuries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    body_area       VARCHAR(100) NOT NULL,
    description     TEXT NOT NULL,
    severity        VARCHAR(20) NOT NULL CHECK (severity IN ('LEVE','MODERADA','GRAVE')),
    started_at      DATE,
    resolved_at     DATE,
    active          BOOLEAN NOT NULL DEFAULT true,
    notes           TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_injuries_student ON student_injuries(student_id);

CREATE TABLE student_notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    author_user_id  BIGINT NOT NULL REFERENCES users(id),
    content         TEXT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_student_notes_student ON student_notes(student_id, created_at DESC);
