CREATE TABLE exercises (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id              BIGINT NOT NULL REFERENCES gyms(id),
    name                VARCHAR(150) NOT NULL,
    slug                VARCHAR(150) NOT NULL,
    description         TEXT,
    technical_notes     TEXT,
    default_measurement VARCHAR(30) NOT NULL DEFAULT 'REPS_WEIGHT'
                        CHECK (default_measurement IN ('REPS_WEIGHT','REPS_ONLY','TIME','DISTANCE','CIRCUIT_REPS')),
    video_url           VARCHAR(500),
    image_url           VARCHAR(500),
    active              BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_exercises_gym_slug UNIQUE (gym_id, slug)
);

CREATE INDEX idx_exercises_gym_active ON exercises(gym_id, active);
CREATE INDEX idx_exercises_search ON exercises(gym_id, name);

CREATE TABLE exercise_tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id      BIGINT NOT NULL REFERENCES gyms(id),
    type        VARCHAR(30) NOT NULL
                CHECK (type IN ('BODY_AREA','MUSCLE_GROUP','MOVEMENT_PATTERN','OBJECTIVE','LEVEL','EQUIPMENT')),
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    CONSTRAINT uk_tag_gym_type_slug UNIQUE (gym_id, type, slug)
);

CREATE INDEX idx_tags_type ON exercise_tags(gym_id, type);

CREATE TABLE exercise_tag_assignments (
    exercise_id     BIGINT NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    tag_id          BIGINT NOT NULL REFERENCES exercise_tags(id) ON DELETE CASCADE,
    PRIMARY KEY (exercise_id, tag_id)
);

CREATE INDEX idx_eta_tag ON exercise_tag_assignments(tag_id);
