INSERT INTO exercise_tags (gym_id, type, name, slug) VALUES
(1, 'BODY_AREA', 'Tren superior', 'tren-superior'),
(1, 'BODY_AREA', 'Zona media', 'zona-media'),
(1, 'BODY_AREA', 'Tren inferior', 'tren-inferior'),
(1, 'BODY_AREA', 'Cuerpo completo', 'cuerpo-completo'),
(1, 'MUSCLE_GROUP', 'Pecho', 'pecho'),
(1, 'MUSCLE_GROUP', 'Espalda', 'espalda'),
(1, 'MUSCLE_GROUP', 'Hombros', 'hombros'),
(1, 'MUSCLE_GROUP', 'Bíceps', 'biceps'),
(1, 'MUSCLE_GROUP', 'Tríceps', 'triceps'),
(1, 'MUSCLE_GROUP', 'Antebrazos', 'antebrazos'),
(1, 'MUSCLE_GROUP', 'Cuádriceps', 'cuadriceps'),
(1, 'MUSCLE_GROUP', 'Isquiotibiales', 'isquiotibiales'),
(1, 'MUSCLE_GROUP', 'Glúteos', 'gluteos'),
(1, 'MUSCLE_GROUP', 'Aductores', 'aductores'),
(1, 'MUSCLE_GROUP', 'Gemelos', 'gemelos'),
(1, 'MUSCLE_GROUP', 'Core', 'core'),
(1, 'MUSCLE_GROUP', 'Lumbares', 'lumbares'),
(1, 'MUSCLE_GROUP', 'Oblicuos', 'oblicuos'),
(1, 'MUSCLE_GROUP', 'Cuello', 'cuello'),
(1, 'MOVEMENT_PATTERN', 'Empuje vertical', 'empuje-vertical'),
(1, 'MOVEMENT_PATTERN', 'Empuje horizontal', 'empuje-horizontal'),
(1, 'MOVEMENT_PATTERN', 'Tirón vertical', 'tiron-vertical'),
(1, 'MOVEMENT_PATTERN', 'Tirón horizontal', 'tiron-horizontal'),
(1, 'MOVEMENT_PATTERN', 'Sentadilla', 'sentadilla'),
(1, 'MOVEMENT_PATTERN', 'Bisagra de cadera', 'bisagra-de-cadera'),
(1, 'MOVEMENT_PATTERN', 'Zancada', 'zancada'),
(1, 'MOVEMENT_PATTERN', 'Rotación', 'rotacion'),
(1, 'MOVEMENT_PATTERN', 'Anti-rotación', 'anti-rotacion'),
(1, 'MOVEMENT_PATTERN', 'Locomoción', 'locomocion'),
(1, 'MOVEMENT_PATTERN', 'Salto', 'salto'),
(1, 'MOVEMENT_PATTERN', 'Isométrico', 'isometrico'),
(1, 'OBJECTIVE', 'Fuerza', 'fuerza'),
(1, 'OBJECTIVE', 'Hipertrofia', 'hipertrofia'),
(1, 'OBJECTIVE', 'Potencia', 'potencia'),
(1, 'OBJECTIVE', 'Resistencia muscular', 'resistencia-muscular'),
(1, 'OBJECTIVE', 'Resistencia cardiovascular', 'resistencia-cardiovascular'),
(1, 'OBJECTIVE', 'Movilidad', 'movilidad'),
(1, 'OBJECTIVE', 'Flexibilidad', 'flexibilidad'),
(1, 'OBJECTIVE', 'Prevención', 'prevencion'),
(1, 'OBJECTIVE', 'Rehabilitación', 'rehabilitacion'),
(1, 'OBJECTIVE', 'Técnica', 'tecnica'),
(1, 'OBJECTIVE', 'Activación', 'activacion'),
(1, 'OBJECTIVE', 'Coordinación', 'coordinacion'),
(1, 'LEVEL', 'Iniciación', 'iniciacion'),
(1, 'LEVEL', 'Intermedio', 'intermedio'),
(1, 'LEVEL', 'Avanzado', 'avanzado'),
(1, 'EQUIPMENT', 'Peso corporal', 'peso-corporal'),
(1, 'EQUIPMENT', 'Mancuernas', 'mancuernas'),
(1, 'EQUIPMENT', 'Barra olímpica', 'barra-olimpica'),
(1, 'EQUIPMENT', 'Barra Z', 'barra-z'),
(1, 'EQUIPMENT', 'Polea', 'polea'),
(1, 'EQUIPMENT', 'Máquina guiada', 'maquina-guiada'),
(1, 'EQUIPMENT', 'Banda elástica', 'banda-elastica'),
(1, 'EQUIPMENT', 'Kettlebell', 'kettlebell'),
(1, 'EQUIPMENT', 'Cajón', 'cajon'),
(1, 'EQUIPMENT', 'Soga (battle ropes)', 'soga-battle-ropes'),
(1, 'EQUIPMENT', 'TRX', 'trx'),
(1, 'EQUIPMENT', 'Bicicleta', 'bicicleta'),
(1, 'EQUIPMENT', 'Elíptica', 'eliptica'),
(1, 'EQUIPMENT', 'Cinta', 'cinta'),
(1, 'EQUIPMENT', 'Remo', 'remo'),
(1, 'EQUIPMENT', 'Disco', 'disco'),
(1, 'EQUIPMENT', 'Slam ball', 'slam-ball'),
(1, 'EQUIPMENT', 'Medicine ball', 'medicine-ball'),
(1, 'EQUIPMENT', 'Bosu', 'bosu'),
(1, 'EQUIPMENT', 'Fitball', 'fitball');
